
### Add Post By Thomas
POST http://localhost:5000/api/blog
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyIsImlkIjoiNjM3ZGI3MDU2MjkzODkzZDdmMTliZTNjIiwiaWF0IjoxNjY5MTgzMjg1LCJleHAiOjE2NjkxODkyODV9.1_a0UoWxzyuEJA8PqSQRK0Ud9-1DeN9DSXfA7v02ZwI
Content-Type: application/json

{
    "title":"What is Mocha?",
    "author":"Thomas Alemayehu",
    "url":"home.com"
}


### Add Post By Abel
POST http://localhost:5000/api/blog
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRob21hczJhbGV4bWVjaEBnbWFpbC5jb20iLCJpZCI6IjYzOTQ5MzQzZDJiMTc1NjcyNDIwNWUyNSIsImlhdCI6MTY3MDY4MzA3OSwiZXhwIjoxNjcwNjg5MDc5fQ.xGcW213ME1uvzpHgZHb3vLKnaaePvUVHFlfe56_g8aA
Content-Type: application/json

{
    "title":"What is Jest?",
    "author":"Abel Alem",
    "url":"home.com"
}

###
GET http://localhost:5000/api/users


### GET ALL Blogs
GET http://localhost:5000/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyIsImlkIjoiNjM5NDhmZjk0YTdjNDBhOGU3MDY4MjdhIiwiaWF0IjoxNjcwNjgwNTczLCJleHAiOjE2NzA2ODY1NzN9.0MKn-bgNvhzk-zw-IwsjGSoBR6Nj53AZaqEQZLyt0Rk

### GET Blog by ID
GET http://localhost:5000/api/blog/6394a11e3a4d9e182d749575
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRob21hczJhbGV4bWVjaEBnbWFpbC5jb20iLCJpZCI6IjYzOTU5ODBkYjc5Zjk5YTJkYjE5YTZkMiIsImlhdCI6MTY3MDc0ODE3NSwiZXhwIjoxNjcwNzU0MTc1fQ.XhmZKnXr7bpV0NkSSRTRP1cIWIknbbLPsPW11cknH14


### Delete Blog by Abel using Thomas
DELETE http://localhost:5000/api/blog/637db871c082f2bbfbe304ad
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyIsImlkIjoiNjM3ZGI3MDU2MjkzODkzZDdmMTliZTNjIiwiaWF0IjoxNjY5MTgzMjg1LCJleHAiOjE2NjkxODkyODV9.1_a0UoWxzyuEJA8PqSQRK0Ud9-1DeN9DSXfA7v02ZwI

### Delete Blog by Abel using Abel
DELETE http://localhost:5000/api/blog/637db871c082f2bbfbe304ad
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFiZWwiLCJpZCI6IjYzN2RiNzJhNjI5Mzg5M2Q3ZjE5YmUzZSIsImlhdCI6MTY2OTE4MzMxMCwiZXhwIjoxNjY5MTg5MzEwfQ.6q-0wtp2Pe-g_6_m_DdOxOY4rjJztAXlz2wLmxqUU98