
### Add Post By Thomas
POST http://localhost:5000/api/blog
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyIsImlkIjoiNjM3ZGI3MDU2MjkzODkzZDdmMTliZTNjIiwiaWF0IjoxNjY5MTgzMjg1LCJleHAiOjE2NjkxODkyODV9.1_a0UoWxzyuEJA8PqSQRK0Ud9-1DeN9DSXfA7v02ZwI
Content-Type: application/json

{
    "title":"What is Mocha?",
    "author":"Thomas Alemayehu",
    "url":"home.com"
}


### Add Post By Abel
POST http://localhost:5000/api/blog
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFiZWwiLCJpZCI6IjYzN2RiNzJhNjI5Mzg5M2Q3ZjE5YmUzZSIsImlhdCI6MTY2OTE4MzMxMCwiZXhwIjoxNjY5MTg5MzEwfQ.6q-0wtp2Pe-g_6_m_DdOxOY4rjJztAXlz2wLmxqUU98
Content-Type: application/json

{
    "title":"What is Jest?",
    "author":"Abel Alem",
    "url":"home.com"
}

###
GET http://localhost:5000/api/users


### GET ALL Blogs
GET http://localhost:5000/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyBBIiwiaWQiOiI2MzdkYWE3Y2JjY2M3NjYzZTM3YjkxMDEiLCJpYXQiOjE2NjkxODI3OTEsImV4cCI6MTY2OTE4ODc5MX0.z5Ko69B1bPWhxeHke35gwoU14e0S1o5wEdv4780io_g

### GET Blog by ID
GET http://localhost:5000/api/blog/637db86fc082f2bbfbe304a9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyBBIiwiaWQiOiI2MzdkYWE3Y2JjY2M3NjYzZTM3YjkxMDEiLCJpYXQiOjE2NjkxODI3OTEsImV4cCI6MTY2OTE4ODc5MX0.z5Ko69B1bPWhxeHke35gwoU14e0S1o5wEdv4780io_g


### Delete Blog by Abel using Thomas
DELETE http://localhost:5000/api/blog/637db871c082f2bbfbe304ad
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRob21hcyIsImlkIjoiNjM3ZGI3MDU2MjkzODkzZDdmMTliZTNjIiwiaWF0IjoxNjY5MTgzMjg1LCJleHAiOjE2NjkxODkyODV9.1_a0UoWxzyuEJA8PqSQRK0Ud9-1DeN9DSXfA7v02ZwI

### Delete Blog by Abel using Abel
DELETE http://localhost:5000/api/blog/637db871c082f2bbfbe304ad
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFiZWwiLCJpZCI6IjYzN2RiNzJhNjI5Mzg5M2Q3ZjE5YmUzZSIsImlhdCI6MTY2OTE4MzMxMCwiZXhwIjoxNjY5MTg5MzEwfQ.6q-0wtp2Pe-g_6_m_DdOxOY4rjJztAXlz2wLmxqUU98