
### Register Thomas
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"thomas2alexmech@gmail.com",
    "password":"mypasswordisgood"
}

####
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"thomasalexmech@gmail.com",
    "password":"mypasswordisgood"
}


### Login Thomas
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"thomas2alexmech@gmail.com",
    "password":"mypasswordisgood"
}

### Register Abel
POST http://localhost:5000/api/user
Content-Type: application/json

{
    "username":"Abel",
    "password":"mypasswordisgood"
}


### Login Abel
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"Abel",
    "password":"mypasswordisbad"
}




### Testing Routes
POST http://localhost:5000/test/populate